{
 "title": "Container Monitoring",
 "tags": [
  "docker",
  "cadvisor"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\".+\"}[1m]) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".+\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/sec" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=~\".+\"}[1m])",
     "legendFormat": "{{ name }} - RX"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{name=~\".+\"}[1m])",
     "legendFormat": "{{ name }} - TX"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Storage" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=~\".+\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "singlestat",
   "gridPos": { "x": 0, "y": 16, "w": 6, "h": 4 },
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\".+\"})"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "x": 6, "y": 16, "w": 6, "h": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"})"
    }
   ]
  }
 ]
}